import Head from 'next/head'
import Footer from '../components/Footer'
import Login from '../components/Login'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex flex-col'>
        {/* navbar */}
        <Navbar />

        {/* body */}
        <Login />

        {/* footer */}
        <Footer />
      </main>
    </>
  )
}
